# This is a basic workflow to help you get started with Actions

name: Discord Notification

on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: ":tada: **The project '{{ EVENT_PAYLOAD.repository.name }}' has been released. Version: {{ EVENT_PAYLOAD.release.tag_name }}**\nChangelog: {{EVENT_PAYLOAD.release.url}}\n{{ toJson(EVENT_PAYLOAD) }}"
